-- local M = {}
--
-- local start = vim.health.start
-- local ok = vim.health.ok
-- local warn = vim.health.warn
-- local error = vim.health.error
--
--
-- function M.check()
--   start("FeelingLight config")
-- end
--
-- return M

