#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" -d "$BASEDIR" -c "$config" $ARGS
}

# run_dotbot 'dotbot/modules/00. update.yaml'
# run_dotbot 'dotbot/modules/shell.yaml'
# run_dotbot 'dotbot/modules/neovim.yaml'
# run_dotbot 'dotbot/modules/vscode.yaml'
# run_dotbot 'dotbot/modules/home.yaml'
run_dotbot 'dotbot/modules/99. test.yaml'

