#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

run_dotbot () {
  local config
  config="$1"
  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" -d "$BASEDIR" -c "$config"
}

# sudo apt-get update

# run_dotbot 'modules/10.shell.yaml'
# run_dotbot 'modules/20.neovim.yaml'
# run_dotbot 'modules/30.gui.yaml'
# run_dotbot 'modules/80.home.yaml'
# run_dotbot 'modules/90.work.yaml'
run_dotbot 'modules/99.test.yaml'

