# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH=$PATH:$HOME/.local/bin

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="false"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="false"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="dd.mm.yyyy"

plugins=(
    gitfast
    sudo
    zsh-autosuggestions
    zsh-syntax-highlighting
    dirhistory
    eza
    zoxide
    colored-man-pages
    pip
    copybuffer
    copypath
    )

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

autovenv() {
    local current_dir="$PWD"

    while true; do
        if [ -f "$current_dir/venv/bin/activate" ]; then
            source "$current_dir/venv/bin/activate"
            return
        fi

        if [ -f "$current_dir/.venv/bin/activate" ]; then
            source "$current_dir/.venv/bin/activate"
            return
        fi

        if [ "$current_dir" = "/" ]; then
            break
        fi

        current_dir=$(dirname "$current_dir")
    done

    if type deactivate >/dev/null 2>&1; then
        deactivate
    fi
}

autoload -U add-zsh-hook
add-zsh-hook chpwd autovenv

autovenv

export PATH=$PATH:$HOME/.local/bin

source /usr/share/doc/fzf/examples/key-bindings.zsh

alias pc="nohup pycharm-community > /dev/null 2>&1 &!"
alias pcc="nohup pycharm-community . > /dev/null 2>&1 &!"

alias clion="nohup clion > /dev/null 2>&1 &!"
alias clionc="nohup clion . > /dev/null 2>&1 &!"

alias dol="nohup dolphin > /dev/null 2>&1 &!"
alias dolc="nohup dolphin . > /dev/null 2>&1 &!"

alias pyv="python3 -m venv venv"
alias uvv="uv venv"
alias ur="uv run"
alias upi="uv pip install"

alias cat="batcat -pp"

# Чтобы rm -rf * не задавал вопросов
setopt localoptions rmstarsilent

